version: '3.4'
networks:
  backend:
services:
  dbmicroservice:
    container_name: dbmicroservices-container
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Exam!1234#
    ports:
      - 1433:1433 
    networks:
      - backend
  library.api:
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: .
      dockerfile: src/LibraryProject/Library.API/Dockerfile
    environment:
    - DB_HOST=dbmicroservice
    - DB_NAME=librarydb
    - SA_PASSWORD=Exam!1234#
    networks:
      - backend
